Tord shell sort fp
KimSvenSand/ToKi pull request #20
Opened 2017-04-17 21:55 UTC by Kazads

2017-04-19 14:50 UTC, KimSvenSand requested changes
Same as the other ones plus some comment

2017-04-19 14:50 UTC, KimSvenSand commented on FPShellSortTord/src/js/Shellsort.js
> +
The naming and structure is a bit hard to understand. Do not mutate input parameters.

2017-04-25 08:55 UTC, emilfolino reviewed
Skapa en kopia av de variabler du vill mutera, så ni undviker side-effects.

2017-04-25 08:55 UTC, emilfolino commented on FPShellSortTord/src/index.js
> +  console.log(array);
ett litet tips: använd `console.log("Unsorted:", array);` så halverar man console.logs och blir lite mer sammanhang.

2017-04-25 08:55 UTC, emilfolino commented on FPShellSortTord/src/js/Shellsort.js
> +  if(length >= 0){
Skapa kopia av array som du muterar istället för array.

2017-04-25 08:55 UTC, emilfolino commented on FPShellSortTord/src/js/Shellsort.js
> +  if(gapSequence[currentGapIndex] > array.length/2){
Muterar currentGapIndex, skapa kopia.

2017-04-25 08:55 UTC, emilfolino commented on FPShellSortTord/src/js/Shellsort.js
> +  if(gapSequence[currentGapIndex] > 0){
Muterar array.

2017-04-25 08:55 UTC, emilfolino commented on FPShellSortTord/src/js/Shellsort.js
> +  if(currentIndex < array.length){
muterar array, currentValue, currentIndex

2017-04-25 08:55 UTC, emilfolino commented on FPShellSortTord/src/js/Shellsort.js
> +  if((currentIndex - currentGap) >= 0 && array[currentIndex - currentGap] > currentValue){
muterar currentIndex, array

2017-05-02 15:45 UTC, closed without merging