Tord shell sort oop
KimSvenSand/ToKi pull request #21
Opened 2017-04-17 21:56 UTC by Kazads

2017-04-19 14:32 UTC, KimSvenSand requested changes
Same changes as before

2017-04-19 14:32 UTC, KimSvenSand commented on OOShellSortTord/src/index.js
> +
Same as the earlier ones.

2017-04-19 14:32 UTC, KimSvenSand commented on OOShellSortTord/es6-test/shellsort_test.js
> +
Wrong testdata

2017-04-25 08:58 UTC, emilfolino reviewed
Ser bra ut, gör det möjligt att instantiera ett objekt utan att sortera.

2017-04-25 08:58 UTC, emilfolino commented on OOShellSortTord/src/js/Shellsort.js
> +    var sortedArray = array;
Separera konstruktor och sorterings funktion.

2017-05-02 15:45 UTC, closed without merging