Tord hanoi fp
KimSvenSand/ToKi pull request #22
Opened 2017-04-17 21:56 UTC by Kazads

2017-04-20 08:33 UTC, KimSvenSand requested changes
Index fix and stuff

2017-04-20 08:33 UTC, KimSvenSand commented on FPHanoiTord/src/js/Hanoi.js
> +
Mutating data here

2017-04-25 09:10 UTC, emilfolino reviewed
Bra kort kod.

2017-04-25 09:10 UTC, emilfolino commented on FPHanoiTord/src/js/Hanoi.js
> +    start = a[0];
Kanske använda `var [copyStart, copyDest, copyAux, copySteps] = hanoi(disk-1, start, aux, dest,steps);` för kortare kod? Även på rad 15.

2017-04-25 09:10 UTC, emilfolino commented on FPHanoiTord/src/js/Hanoi.js
> +  if(disk == 1){
Muterar variabler så returnera copyStart, copyDest, copyAux, copySteps

2017-05-02 15:45 UTC, closed without merging