Tord hanoi oop
KimSvenSand/ToKi pull request #23
Opened 2017-04-17 21:56 UTC by Kazads

2017-04-20 08:06 UTC, KimSvenSand requested changes
Perhaps structure a bit more with classes and objects. Comment some more to make it more clear what the algorithm does. :octocat:

2017-04-20 08:06 UTC, KimSvenSand commented on OOHanoiTord/src/js/Hanoi.js
> +   // 1-FROM ROD, 2-USING ROD, 3-TO ROD
Remove this comment

2017-04-20 08:06 UTC, KimSvenSand commented on OOHanoiTord/src/js/Hanoi.js
> +  var pegs = [[], [], []];
Remove this

2017-04-20 08:06 UTC, KimSvenSand commented on OOHanoiTord/src/js/Hanoi.js
> +  //console.log("Number of moves: "+numberOfMoves);
Remove this comment

2017-04-20 08:06 UTC, KimSvenSand commented on OOHanoiTord/src/js/Hanoi.js
> +        pegMin = (oldPegMin + dir + 3) % 3;
pegMin might be a misleading name

2017-04-25 10:10 UTC, emilfolino reviewed
Ser bra ut.

2017-05-02 15:45 UTC, closed without merging