tord dijkstras fp
KimSvenSand/ToKi pull request #25
Opened 2017-04-17 21:57 UTC by Kazads

2017-04-20 09:46 UTC, KimSvenSand requested changes
Be careful with mutating data. Okay to mutate local data in functions. Some more structure and better naming  of functions. Try to use filter and map if possible. Use input -> output thinking.

2017-04-20 09:46 UTC, KimSvenSand commented on FPDijkstrasTord/src/js/Dijkstras.js
> +
Copyyyyy cats :octocat:

2017-04-25 10:16 UTC, emilfolino reviewed
Undvik mutation, skapa kopior.

2017-04-25 10:16 UTC, emilfolino commented on FPDijkstrasTord/src/js/Dijkstras.js
> +  if(length > 1){
Muterar path and dist.

2017-04-25 10:16 UTC, emilfolino commented on FPDijkstrasTord/src/js/Dijkstras.js
> +  if(unvisitedNodes.length > 0 && unvisitedNodes.indexOf(endNode) != -1){
muterar path och dist

2017-04-25 10:16 UTC, emilfolino commented on FPDijkstrasTord/src/js/Dijkstras.js
> +  if(graphLength > 0){
muterar currentNode och currentValue

2017-04-25 10:16 UTC, emilfolino commented on FPDijkstrasTord/src/js/Dijkstras.js
> +  if(edgeLength > 0){
Muterar path och dist.

2017-04-25 10:16 UTC, emilfolino commented on FPDijkstrasTord/src/js/Dijkstras.js
> +  if(unvisitedLength > 0){
Muterar newArray.

2017-05-02 15:45 UTC, closed without merging