tord binary search tree oop
KimSvenSand/ToKi pull request #27
Opened 2017-04-17 21:58 UTC by Kazads

2017-04-19 13:35 UTC, KimSvenSand commented on OOBinarySearchTreeTord/es6-test/bst_test.js
> +describe('BinarySearchTree', function() {
You're not using our test data. Make sure that insert works correctly without using untested functions.

2017-04-19 13:49 UTC, KimSvenSand requested changes
Some small stuff, and we will have to test this with the new tests as well :)

2017-04-19 13:49 UTC, KimSvenSand commented on OOBinarySearchTreeTord/es6-test/bst_test.js
> +describe('BinarySearchTree', function() {
You're not using our test-date. Make sure to test for example insert without using untested functions.

2017-04-19 13:49 UTC, KimSvenSand commented on OOBinarySearchTreeTord/src/index.js
> +  let t0 = new Date();
You're not measuring the time of anything.

2017-04-19 13:49 UTC, KimSvenSand commented on OOBinarySearchTreeTord/src/js/BinarySearchTree.js
> +        while(node != null){
maybe use your insert function here?

2017-04-19 13:49 UTC, KimSvenSand commented on OOBinarySearchTreeTord/src/js/BinarySearchTree.js
> +
Return Node instead of key, since key is the input.

2017-04-25 10:22 UTC, emilfolino reviewed
Bra implementation.

2017-04-25 10:22 UTC, emilfolino commented on OOBinarySearchTreeTord/src/js/BinarySearchTree.js
> +  constructor(tree) {
Dela upp instantiering och skapande av träd? Och använd insert, är mer DRY.

2017-05-02 15:46 UTC, closed without merging